// Mock Yelp-like restaurant data for Step 1
// This shape matches what our UI expects
export const MOCK_RESTAURANTS = [
  {
    id: 'yelp-1',
    name: 'Spice Symphony',
    image:
      'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2070&auto=format&fit=crop',
    rating: 4.5,
    reviewCount: 1287,
    price: '$$','phone': '+1 212-555-0111',
    address: '150 E 50th St, New York, NY 10022',
    coordinates: {latitude: 40.757, longitude: -73.972},
    categories: ['Indian', 'Seafood', 'Bar'],
    distance: '0.6',
    isClosed: false,
    url: 'https://www.yelp.com/biz/spice-symphony-new-york',
    specialties: 'Coastal curries, tandoor platters, and cocktails',
    reservations: true,
    delivery: true,
    pickup: true,
  },
  {
    id: 'yelp-2',
    name: 'Little Shanghai',
    image:
      'https://images.unsplash.com/photo-1604908554027-9d5d2aa6a5b8?q=80&w=2070&auto=format&fit=crop',
    rating: 4.3,
    reviewCount: 934,
    price: '$$','phone': '+1 212-555-0198',
    address: '22 Pell St, New York, NY 10013',
    coordinates: {latitude: 40.715, longitude: -73.997},
    categories: ['Chinese', 'Dumplings', 'Noodles'],
    distance: '2.3',
    isClosed: false,
    url: 'https://www.yelp.com/biz/little-shanghai-new-york',
    specialties: 'Soup dumplings and hand-pulled noodles',
    reservations: false,
    delivery: true,
    pickup: true,
  },
  {
    id: 'yelp-3',
    name: 'Green Garden',
    image:
      'https://images.unsplash.com/photo-1544025162-4c2f4f6a6912?q=80&w=2070&auto=format&fit=crop',
    rating: 4.7,
    reviewCount: 642,
    price: '$$','phone': '+1 212-555-0142',
    address: '77 7th Ave, New York, NY 10011',
    coordinates: {latitude: 40.739, longitude: -73.999},
    categories: ['Vegan', 'Salad', 'Healthy'],
    distance: '1.6',
    isClosed: false,
    url: 'https://www.yelp.com/biz/green-garden-new-york',
    specialties: 'Plant-based bowls and cold-pressed juices',
    reservations: false,
    delivery: true,
    pickup: true,
  },
  {
    id: 'yelp-4',
    name: 'Pasta & Co.',
    image:
      'https://images.unsplash.com/photo-1523986371872-9d3ba2e2f642?q=80&w=2070&auto=format&fit=crop',
    rating: 4.2,
    reviewCount: 512,
    price: '$$','phone': '+1 212-555-0175',
    address: '401 W 14th St, New York, NY 10014',
    coordinates: {latitude: 40.741, longitude: -74.007},
    categories: ['Italian', 'Pasta', 'Wine Bar'],
    distance: '1.1',
    isClosed: false,
    url: 'https://www.yelp.com/biz/pasta-and-co-new-york',
    specialties: 'House-made pasta and Tuscan wines',
    reservations: true,
    delivery: false,
    pickup: true,
  },
  {
    id: 'yelp-5',
    name: 'Burger Hub',
    image:
      'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=2070&auto=format&fit=crop',
    rating: 4.0,
    reviewCount: 2200,
    price: '$','phone': '+1 212-555-0100',
    address: '5th Ave & W 34th St, New York, NY 10001',
    coordinates: {latitude: 40.748, longitude: -73.985},
    categories: ['Burgers', 'Fast Food'],
    distance: '0.9',
    isClosed: false,
    url: 'https://www.yelp.com/biz/burger-hub-new-york',
    specialties: 'Smash burgers and loaded fries',
    reservations: false,
    delivery: true,
    pickup: true,
  },
];
